---
- name: Install Vector | DNF install
  become: true
  ansible.builtin.dnf:
    name: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.{{ ansible_architecture }}.rpm
    state: present
  notify: restart vector service
