---
- name: restart vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: restarted
    daemon_reload: true
  when: 
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution'] == "Ubuntu"